ruby '2.1.2'
source "https://rubygems.org"
gem 'twilio-ruby'
gem 'sinatra'
gem 'thin'
gem 'forecast_io'
gem 'geocoder'
gem 'nokogiri'
gem 'hashie'
gem 'json', '~> 1.7.7'
gem 'wikipedia-client'
gem 'google_directions'
gem 'dicechucker'
gem 'htmlentities'
gem 'hpricot'
gem 'httparty'
